Repository BME-MIT-IET/iet-hf-2022-dzsungelharcosok, pull requests merged in 2022-05, with the labels that each got.

#24 Seperate files in folders
  doc/Clean_code_doc.md
  doc/Documentation.md
  src/main/java/com/csv2rdf/csv/CSV2RDF.java
  src/main/java/com/csv2rdf/csv/Generators/BNodeGenerator.java
  src/main/java/com/csv2rdf/csv/Generators/ConstantValueGenerator.java
  src/main/java/com/csv2rdf/csv/Generators/StatementGenerator.java
  src/main/java/com/csv2rdf/csv/Generators/TemplateLiteralGenerator.java
  src/main/java/com/csv2rdf/csv/Generators/TemplateURIGenerator.java
  src/main/java/com/csv2rdf/csv/Generators/TemplateValueGenerator.java
  src/main/java/com/csv2rdf/csv/Generators/ValueGenerator.java
  src/main/java/com/csv2rdf/csv/Providers/RowNumberProvider.java
  src/main/java/com/csv2rdf/csv/Providers/RowValueProvider.java
  src/main/java/com/csv2rdf/csv/Providers/UUIDProvider.java
  src/main/java/com/csv2rdf/csv/Providers/ValueProvider.java
  src/main/java/com/csv2rdf/csv/Template.java
  src/main/java/com/csv2rdf/csv/ValueGenerator.java
  src/test/java/StepDefinitions/bNodeGenerateSteps.java
Labels: enhancement

#27 Fix testngxml location so that docker runs correctly
  build.cmd
  pom.xml
  src/test/resources/testng.xml
Labels: bug

#25 Create the documentation for the project
  IET-HF.md
  README.md
  doc/CleanCode.md
  doc/Clean_code_doc.md
  doc/Cucumber_test.md
  doc/Docker.md
  doc/Documentation.md
  doc/GithubActions.md
  doc/Maven.md
  doc/SonarCloud.md
  doc/StressTest.md
  doc/images/1,000,000.png
  doc/images/100,000.png
  doc/images/10000.png
  doc/images/11,000,000.png
  doc/images/2,000,000.png
  doc/images/200,000.png
  doc/images/3,000,000.png
  doc/images/3000.png
  doc/images/35000.png
  doc/images/4,000,000.png
  doc/images/400,000.png
  doc/images/500,000.png
  doc/images/500.png
  doc/images/600,000.png
  doc/images/800,000.png
  doc/images/basicrun.png
  doc/images/docker1.png
  doc/images/docker2.png
  doc/images/files-after.png
  doc/images/files-before.png
  doc/images/maven.png
  dzsungelharcosok-munkanapló.pdf
Labels: documentation
